### ISSUE TITLE
[Bug]: Segmentation Fault - Flipt Client Node

### ISSUE THREAD

**Issue by SamuelCabralCruz** [flipt-io/flipt-client-sdks#169]
### Bug Description

I am opening this bug here since I don't have the bug report option in the flipt-io/flipt-client-sdks repository.

I am getting a segmentation fault when using the flipt client sdk for node.

Based on my researches, everything seems to point to the ffi call being made to allocate memory.
I think it has something to do with the fact that I am using a MacBook Pro M1.

### Version Info

MacBook Pro
Chip: Apple M1 Pro
macOS: Sonoma 14.3.1

library:
@flipt-io/flipt-client: 0.4.2

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

I am trying to write e2e evaluation tests for the local and remove evaluation processes.
These tests would serve as a kinda contract testing layer to easily distinguish internal vs provider issues.

Here is an example:

```
describe('evaluation', () => {
  let client: FliptEvaluationClient;
  let entityId: string;
  let context: E2eEvaluationContext;

  beforeAll(() => {
    client = new FliptEvaluationClient('e2e', { url: 'http://localhost:8080' });
  });

  afterAll(() => {
    client.close();
  });

  beforeEach(() => {
    entityId = uuid.v4();
    context = {};
  });

  describe('boolean-flag', () => {
    describe('simple', () => {
      describe('disabled', () => {
        const flagKey = 'prd0002-disabled';
        let observed: BooleanResult;

        beforeEach(() => {
          observed = client.evaluateBoolean(flagKey, entityId, context);
        });

        it('should return false', () => {
          expect(observed.status).toEqual('success');
          expect(observed.error_message).toBeNull();
          expect(observed.result!.enabled).toBe(false);
          expect(observed.result!.reason).toBe('MATCH_EVALUATION_REASON');
        });
      });
    });
  });
});
```

**Comment by markphelps** [comment]
@jfbreault @SamuelCabralCruz would you be able to export the Flipt state that you are running the tests against?

I tried to reproduce in #173 but when I run the updated test locally I only get a failure because I don't have the correct state for the added `boolean-flag/simple/disabled` test:

```
    boolean-flag
      simple
        disabled
          ✕ should return false (10 ms)

  ● evaluation › boolean-flag › simple › disabled › should return false

    expect(received).toBe(expected) // Object.is equality

    Expected: "MATCH_EVALUATION_REASON"
    Received: "DEFAULT_EVALUATION_REASON"

      175 |           expect(observed.error_message).toBeNull();
      176 |           expect(observed.result!.enabled).toBe(false);
    > 177 |           expect(observed.result!.reason).toBe('MATCH_EVALUATION_REASON');
          |                                           ^
      178 |         });
      179 |       });
      180 |     });

      at Object.<anonymous> (src/evaluation.test.ts:177:43)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.486 s, estimated 2 s
```

**Comment by markphelps** [comment]
Also, would you mind attaching the error output/segfault you are seeing when running tests? and more info about your node and npm versions/etc?

```
» node -v
v18.19.0
» npm -v
10.2.3
```

**Comment by SamuelCabralCruz** [comment]
```
flipt export --namespaces e2e
version: "1.2"
namespace: e2e
flags:
- key: prd0002-disabled
  name: disabled
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: prd0000-4a845c25fa825feac1813bf514e0ca76
- key: prd0002-enabled
  name: enabled
  type: BOOLEAN_FLAG_TYPE
  enabled: false
  rollouts:
  - segment:
      key: prd0000-4a845c25fa825feac1813bf514e0ca76
      value: true
segments:
- key: prd0000-4a845c25fa825feac1813bf514e0ca76
  name: or-always
  constraints:
  - type: BOOLEAN_COMPARISON_TYPE
    property: (╯°□°)╯︵ ┻━┻
    operator: notpresent
  match_type: ANY_MATCH_TYPE
```

```
╭─Samuel.Cabralcruz at MacBook Pro (2) ❰2024/03/19⌛16:44:02❱
│ in ~/Documents/ticketmaster/feature-flag/local on feat/e2e-evaluation-tests✘
╰─◉ node -v
v20.10.0
╭─Samuel.Cabralcruz at MacBook Pro (2) ❰2024/03/19⌛16:44:04❱
│ in ~/Documents/ticketmaster/feature-flag/local on feat/e2e-evaluation-tests✘
╰─◉ npm -v
10.2.3
```

I don't have the core dump available right now. Will provide later on.
