### ISSUE TITLE
swift sdk not installable as swift package (per install instructions)

### ISSUE THREAD

**Issue by EXC-BAD-ACCESS** [flipt-io/flipt-client-sdks#670]
instructions say:

```
Or add it directly through Xcode:

File > Add Package Dependencies
Enter package URL: https://github.com/flipt-io/flipt-client-swift
```

doing so results in an error:

<img width="1408" alt="Image" src="https://github.com/user-attachments/assets/0dfea0bb-02ed-472e-9980-4d02cf1060c6" />

clicking "Add Anyway" results in an empty unusable package.

<img width="1520" alt="Image" src="https://github.com/user-attachments/assets/bc1a5959-bac7-4ff0-bfc7-0a0f48ab16dc" />

I was able to get it working, but i had to:

- clone this repo
- cd flipt-client-sdks/flipt-engine-ffi
- ./build swift
- in Xcode: Add Local > choose path to flipt-client-sdks/flipt-client-swift

<img width="1520" alt="Image" src="https://github.com/user-attachments/assets/5866aa9c-8d9a-4638-89ae-9606463c63f0" />

**Comment by markphelps** [comment]
Thanks @EXC-BAD-ACCESS for reporting. Is there a better way to package/distribute this library so its more easily installable via swift?

**Comment by EXC-BAD-ACCESS** [comment]
i think you need 2 additional things added to your github workflow.

- on any push to any of the files in https://github.com/flipt-io/flipt-client-sdks/tree/main/flipt-client-swift you need to sync that change to https://github.com/flipt-io/flipt-client-swift 
- on any release you need to copy each of the built libfliptengine.a libraries to it's respective folder in https://github.com/flipt-io/flipt-client-swift/Sources/FliptEngineFFI.xcframework

i hesitate to put up a PR for any of the above as i've never worked with github release workflows, but i think the first part would look like the following:

a new file `.github/client-swift-sync.yml` with contents similar to:
```
flipt-io/flipt-client-swift:
  - /
```

and a new file `.github/workflows/client-swift-sync.yml`

```
name: Swift Sync

on:
  push:
    branches:
      - main
    paths:
      - 'flipt-client-swift/**'
  workflow_dispatch:

jobs:
  sync:
    name: Sync Client Swift Folder
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run file sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.CLIENT_SWIFT_SYNC }}
          IS_FINE_GRAINED: true
          CONFIG_PATH: .github/client-swift-sync.yml
          SKIP_PR: true
          COMMIT_PREFIX: 🔄 Workflow in 'flipt-io/flipt-client-sdks'
```

being sure to change `GH_PAT: ${{ secrets.CLIENT_SWIFT_SYNC }}` with valid pointer to a personal acess token for the https://github.com/flipt-io/flipt-client-swift repo

for the second part it sort of looks to me like you're generating all the correct files in https://github.com/flipt-io/flipt-client-sdks/blob/main/.github/workflows/package-ffi-engine.yml, you would need to add a piece which copies the built files at `target/${{ matrix.platform.target}}/release/libfliptengine.a` to `https://github.com/flipt-io/flipt-client-swift/Sources/FliptEngineFFI.xcframework/<new variable name>` because a mapping needs to occur from:

```
matrix.platform.target         destination_folder_name
aarch64-apple-ios        ->    ios-arm64
aarch64-apple-ios-sim    ->    ios-arm64-simulator
aarch64-apple-darwin     ->    macos-arm64
x86_64-apple-darwin      ->    macos-x86_64
```
